#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumBribes function below.
def minimumBribes(q):
    times = 0
    l = len(q)
    for i in range(l,1,-1):
        if q[i-1] != i:
            if q[i-2] == i:
                times += 1
                q[i-2] = q[i-1]
            elif i>2 and q[i-3] == i:
                times += 2
                q[i-3] = q[i-2]
                q[i-2] = q[i-1]
            else:
                print("Too chaotic")
                return None

    print(times)
    return None

if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        n = int(input())

        q = list(map(int, input().rstrip().split()))

        minimumBribes(q)
